apiVersion: v1
kind: Service
metadata:
  name: data-processor-webserver-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4545
  selector:
    app: data-processor-webserver
